// variables.ts

import { ToDoListFormat } from '../interfaces';

export const testToDos: ToDoListFormat[] = [
  { index: 0, ToDo: 'Do the laundry' },
  { index: 1, ToDo: 'Walk the dog' },
  { index: 2, ToDo: 'Buy groceries' },
  { index: 3, ToDo: 'Clean the house' },
  { index: 4, ToDo: 'Study for exam' },
  { index: 5, ToDo: 'Call mom' },
  { index: 6, ToDo: 'Go for a run' },
  { index: 7, ToDo: 'Write report' },
  { index: 8, ToDo: 'Cook dinner' },
  { index: 9, ToDo: 'Read book' },
  { index: 10, ToDo: 'Practice guitar' },
  { index: 11, ToDo: 'Water plants' },
  { index: 12, ToDo: 'Attend meeting' },
  { index: 13, ToDo: 'Pay bills' },
  { index: 14, ToDo: 'Fix car' },
  { index: 15, ToDo: 'Volunteer at shelter' },
  { index: 16, ToDo: 'Plan vacation' },
  { index: 17, ToDo: 'Learn new recipe' },
  { index: 18, ToDo: 'Organize files' },
  { index: 19, ToDo: 'Paint the fence' },
  { index: 20, ToDo: 'Update resume' },
  { index: 21, ToDo: 'Watch movie' },
  { index: 22, ToDo: 'Start blog' },
  { index: 23, ToDo: 'Visit dentist' },
  { index: 24, ToDo: 'Fix leaking faucet' },
  { index: 25, ToDo: 'Practice meditation' },
  { index: 26, ToDo: 'Clean out closet' },
  { index: 27, ToDo: 'Call friend' },
  { index: 28, ToDo: 'Go to gym' },
  { index: 29, ToDo: 'Research new phone' },
  { index: 30, ToDo: 'Write poem' },
  { index: 31, ToDo: 'Schedule appointment' },
  { index: 32, ToDo: 'Play video game' },
  { index: 33, ToDo: 'Take dog to vet' },
  { index: 34, ToDo: 'Attend webinar' },
  { index: 35, ToDo: 'Buy gifts' },
  { index: 36, ToDo: 'Explore new hobby' },
  { index: 37, ToDo: 'Fix bike' },
  { index: 38, ToDo: 'Create budget' },
  { index: 39, ToDo: 'Plant flowers' },
  { index: 40, ToDo: 'Research vacation spots' },
  { index: 41, ToDo: 'Read news' },
  { index: 42, ToDo: 'Attend workshop' },
  { index: 43, ToDo: 'Cook new recipe' },
  { index: 44, ToDo: 'Update software' },
];
